name: s3 deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'

      - name: build
        run: ls -alh && hugo -D && hugo -v deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.JLCOM_S3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.JLCOM_S3_AWS_SECRET_ACCESS_KEY }}
